== Preface

To reach the shared objectives outlined in the joint strategy for marine biodiversity data, OBIS and GBIF will develop:

*	Clear pathways to support holders of marine biodiversity data to publish their datasets using interoperable data standards and flexible data structures, ensuring that full data provenance, lineage and attribution is retained
*	Mechanisms to enable efficient, regular and effective collaboration and communication among the secretariats, nodes and relevant partners at global, regional, national and thematic levels, based on clear guidance and support from the OBIS and GBIF governing bodies.
*	Joint training resources to support information exchange and capacity development across the GBIF and OBIS communities of practice
*	Joint communication resources, in which the respective roles of GBIF and OBIS, as well as the collaboration between them, are effectively communicated through consistent messaging, and are well understood by all relevant stakeholders and audiences

The following actions and suggested specific tasks are proposed. Those in bold are considered priorities by the partnership. Detailed timelines and budgeting for each task will be scheduled into the respective work programme cycles for GBIF and OBIS, taking account of the financial and human resources available and balancing other priorities. A regular review of progress on these items will determine whether implementation is on track, or if more resources are needed to accelerate progress. 

NOTE: Implementation/work plan to be revised annually
